const { createClient } = require('@supabase/supabase-js');

// Initialize Supabase
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

module.exports = async (req, res) => {
  // GET handler for testing connectivity
  if (req.method === 'GET') {
    return res.status(200).json({ status: 'active', message: 'SePay Webhook is ready for POST requests' });
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const data = req.body;
    console.log('Received SePay Webhook:', data);

    // 1. Get transfer content (description)
    // SePay sends the transfer content in the 'content' field
    const content = data.content || '';
    
    // 2. Extract Order ID from content
    // Our order IDs are prefixed with NTPT (e.g., NTPT1715875200)
    const orderIdMatch = content.match(/NTPT\d+/i);
    
    if (orderIdMatch) {
      const orderIdPart = orderIdMatch[0].toUpperCase();
      
      // We need to find the order in our database. 
      // Note: Our database stores UUIDs as primary keys, but we might have a separate order_code 
      // or we just use the purchase_date/id substring. 
      // Wait, in my previous code for sanpham.html, I generated: 
      // const orderId = 'NTPT' + Math.floor(Date.now() / 1000);
      // But I didn't save this "orderId" string into the 'orders' table! 
      // I saved the UUID generated by Supabase.
      
      // I need to add a column 'order_code' to the 'orders' table to store this NTPT... string.
      
      // For now, I'll assume we find the order where order_code = orderIdPart
      const { data: order, error: findError } = await supabase
        .from('orders')
        .select('*')
        .eq('order_code', orderIdPart)
        .eq('status', 'pending')
        .single();

      if (order) {
        // 3. Update order status to success
        const { error: updateError } = await supabase
          .from('orders')
          .update({ status: 'success' })
          .eq('id', order.id);

        if (updateError) {
          console.error('Error updating order status:', updateError);
          return res.status(500).json({ success: false, error: 'Database update failed' });
        }

        console.log(`Order ${orderIdPart} updated to success.`);
        return res.status(200).json({ success: true, message: 'Order updated' });
      } else {
        console.log(`No pending order found for code: ${orderIdPart}`);
        return res.status(200).json({ success: false, message: 'No matching order' });
      }
    }

    return res.status(200).json({ success: false, message: 'No order code found in content' });
  } catch (error) {
    console.error('Webhook Error:', error);
    return res.status(500).json({ success: false, error: error.message });
  }
};
